name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: check grammar
      id: check-grammar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: check grammar
        setup-command: ". ./tests/setup_requirements.sh"
        command: ". ./tests/test_grammar.sh"
        timeout: 1
        max-score: 2
    - name: all lines in the function
      id: all-lines-in-the-function
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: all lines in the function
        setup-command: ". ./tests/setup_requirements.sh"
        command: ". ./tests/test_all_lines.sh"
        timeout: 1
        max-score: 1
    - name: test result
      id: test-result
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test result
        setup-command: ". ./tests/setup_requirements.sh"
        command: ". ./tests/test_results.sh"
        timeout: 2
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECK-GRAMMAR_RESULTS: "${{steps.check-grammar.outputs.result}}"
        ALL-LINES-IN-THE-FUNCTION_RESULTS: "${{steps.all-lines-in-the-function.outputs.result}}"
        TEST-RESULT_RESULTS: "${{steps.test-result.outputs.result}}"
      with:
        runners: check-grammar,all-lines-in-the-function,test-result
